<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <RoslynVersion>5.6.0</RoslynVersion>
    <CommandLineParserVersion>2.9.1</CommandLineParserVersion>
    <FileSystemGlobbingVersion>10.0.9</FileSystemGlobbingVersion>
    <XunitVersion>2.9.3</XunitVersion>
    <XunitRunnerVersion>3.1.5</XunitRunnerVersion>
    <TestSdkVersion>18.8.1</TestSdkVersion>
    <CoverletVersion>10.0.1</CoverletVersion>
    <AkkaVersion>1.5.70</AkkaVersion>
    <RazorLanguageVersion>6.0.36</RazorLanguageVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
    <PackageVersion Include="CommandLineParser" Version="$(CommandLineParserVersion)" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="$(FileSystemGlobbingVersion)" />
    <PackageVersion Include="Akka.Streams" Version="$(AkkaVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Razor.Language" Version="$(RazorLanguageVersion)" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="xunit" Version="$(XunitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageVersion Include="coverlet.collector" Version="$(CoverletVersion)" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>
</Project>
