<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <RoslynVersion>4.13.0</RoslynVersion>
    <CommandLineParserVersion>2.9.1</CommandLineParserVersion>
    <FileSystemGlobbingVersion>9.0.0</FileSystemGlobbingVersion>
    <XunitVersion>2.9.3</XunitVersion>
    <XunitRunnerVersion>3.0.2</XunitRunnerVersion>
    <TestSdkVersion>17.12.0</TestSdkVersion>
    <CoverletVersion>6.0.4</CoverletVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
    <PackageVersion Include="CommandLineParser" Version="$(CommandLineParserVersion)" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="$(FileSystemGlobbingVersion)" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="xunit" Version="$(XunitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageVersion Include="coverlet.collector" Version="$(CoverletVersion)" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>
