namespace Slopwatch.Suppression;

/// <summary>
/// Defines the standard categories for Slopwatch rule suppressions.
/// </summary>
/// <remarks>
/// <para>
/// These categories help classify suppressions and make it easier to audit
/// and analyze why rules are being suppressed across a codebase.
/// </para>
///
/// <para>
/// When using <see cref="SlopwatchSuppressAttribute"/>, you can pass these
/// category names as strings, or use the constants defined in this class
/// for type safety and IntelliSense support.
/// </para>
/// </remarks>
public static class SuppressionCategory
{
    /// <summary>
    /// Platform-specific code (Windows-only, Linux-only, ARM vs x64, etc.).
    /// </summary>
    /// <remarks>
    /// Use this category when code or tests are specific to a particular platform,
    /// operating system, or architecture. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Tests requiring Windows COM components</description></item>
    /// <item><description>Linux-specific system calls</description></item>
    /// <item><description>Architecture-specific optimizations (ARM, x64, x86)</description></item>
    /// <item><description>Platform-specific APIs not available in cross-platform contexts</description></item>
    /// </list>
    /// </remarks>
    public const string Platform = "Platform";

    /// <summary>
    /// Interop with native code, COM, P/Invoke, unmanaged memory.
    /// </summary>
    /// <remarks>
    /// Use this category for code that interoperates with native libraries or
    /// unmanaged code. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>P/Invoke declarations requiring unsafe code</description></item>
    /// <item><description>COM interop with unmanaged memory</description></item>
    /// <item><description>Native library integration (C/C++ libraries)</description></item>
    /// <item><description>Direct memory access for performance</description></item>
    /// </list>
    /// </remarks>
    public const string Interop = "Interop";

    /// <summary>
    /// External dependencies not available (database, API, infrastructure).
    /// </summary>
    /// <remarks>
    /// Use this category when code depends on external resources that may not
    /// be available in all environments. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Database servers not available in CI</description></item>
    /// <item><description>External APIs or web services</description></item>
    /// <item><description>Cloud infrastructure (Azure, AWS, GCP)</description></item>
    /// <item><description>Network resources requiring VPN or special access</description></item>
    /// </list>
    /// </remarks>
    public const string External = "External";

    /// <summary>
    /// Auto-generated code that can't be modified (EF migrations, gRPC, Swagger, etc.).
    /// </summary>
    /// <remarks>
    /// Use this category for code generated by tools or frameworks that you
    /// don't control. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Entity Framework migrations</description></item>
    /// <item><description>gRPC/protobuf generated code</description></item>
    /// <item><description>OpenAPI/Swagger client generation</description></item>
    /// <item><description>Designer-generated UI code (WinForms, WPF)</description></item>
    /// <item><description>Source generators output</description></item>
    /// </list>
    /// </remarks>
    public const string Generated = "Generated";

    /// <summary>
    /// Test-driven development - feature not yet implemented (red phase).
    /// </summary>
    /// <remarks>
    /// Use this category for tests written before the implementation exists,
    /// following TDD practices. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Tests for features not yet implemented</description></item>
    /// <item><description>Tests disabled during major refactoring</description></item>
    /// <item><description>Tests awaiting dependent team's API changes</description></item>
    /// <item><description>Exploratory tests for planned features</description></item>
    /// </list>
    /// </remarks>
    public const string TDD = "TDD";

    /// <summary>
    /// Performance-critical code requiring unsafe patterns or optimizations.
    /// </summary>
    /// <remarks>
    /// Use this category for code where performance requirements necessitate
    /// patterns that would normally be considered problematic. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Unsafe code for zero-allocation operations</description></item>
    /// <item><description>Pointer arithmetic for performance</description></item>
    /// <item><description>Manual memory management in hot paths</description></item>
    /// <item><description>SIMD optimizations requiring special patterns</description></item>
    /// </list>
    /// </remarks>
    public const string Performance = "Performance";

    /// <summary>
    /// Test infrastructure or testing-specific patterns (rate limit tests, timing tests, etc.).
    /// </summary>
    /// <remarks>
    /// Use this category for test code where the pattern being flagged is actually
    /// what's being tested. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Rate limiting tests requiring actual delays</description></item>
    /// <item><description>Timeout behavior validation</description></item>
    /// <item><description>Retry logic testing</description></item>
    /// <item><description>Debounce/throttle mechanism testing</description></item>
    /// <item><description>Intentional exception suppression in test helpers</description></item>
    /// </list>
    /// </remarks>
    public const string Testing = "Testing";

    /// <summary>
    /// Legacy code with planned refactoring or migration path.
    /// </summary>
    /// <remarks>
    /// Use this category for existing code that has known issues but is scheduled
    /// for refactoring or replacement. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Code scheduled for refactoring (with issue reference)</description></item>
    /// <item><description>Code being gradually migrated to new patterns</description></item>
    /// <item><description>Deprecated features being phased out</description></item>
    /// <item><description>Technical debt with documented remediation plan</description></item>
    /// </list>
    /// <strong>Note:</strong> Always include an issue URL when using this category.
    /// </remarks>
    public const string Legacy = "Legacy";

    /// <summary>
    /// Third-party library quirks, bugs, or limitations.
    /// </summary>
    /// <remarks>
    /// Use this category when working around issues in external libraries or
    /// frameworks you don't control. Common scenarios include:
    /// <list type="bullet">
    /// <item><description>Nullability issues in third-party libraries</description></item>
    /// <item><description>Obsolete API usage in libraries not yet updated</description></item>
    /// <item><description>Interface implementation requirements that trigger warnings</description></item>
    /// <item><description>Workarounds for known library bugs</description></item>
    /// </list>
    /// <strong>Note:</strong> Consider including an issue URL referencing the upstream bug.
    /// </remarks>
    public const string Library = "Library";

    /// <summary>
    /// Gets all valid suppression category names.
    /// </summary>
    /// <returns>An array of all valid category names.</returns>
    public static string[] GetAllCategories()
    {
        return new[]
        {
            Platform,
            Interop,
            External,
            Generated,
            TDD,
            Performance,
            Testing,
            Legacy,
            Library
        };
    }

    /// <summary>
    /// Checks if a given category name is valid.
    /// </summary>
    /// <param name="category">The category name to validate.</param>
    /// <returns>True if the category is valid; otherwise, false.</returns>
    public static bool IsValid(string category)
    {
        if (string.IsNullOrWhiteSpace(category))
            return false;

        var allCategories = GetAllCategories();
        return System.Array.Exists(allCategories,
            c => c.Equals(category, System.StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Gets a formatted string describing all valid categories for error messages.
    /// </summary>
    /// <returns>A comma-separated list of all valid category names.</returns>
    public static string GetValidCategoriesDescription()
    {
        return string.Join(", ", GetAllCategories());
    }
}
